enum ActionTypes {
  SET_USER_LIST = "SET_USER_LIST",
  SELECT_USER = "SELECT_USER",
  UPDATE_USER_FORM = "UPDATE_USER_FORM",
  RESET_USER_FORM = "RESET_USER_FORM",
  UPDATE_USER_LIST = "UPDATE_USER_LIST",
  REMOVE_USER_FROM_LIST = "REMOVE_USER_FROM_LIST",
  TOGGLE_USER_FORM = "TOGGLE_USER_FORM",
  INSERT_INTO_USER_LIST = "INSERT_INTO_USER_LIST",
  SET_LOADING_LIST = "SET_LOADING_LIST",
  SET_UPLOADING_AVATAR = "SET_UPLOADING_AVATAR",
  SET_SUMMITTING_USER_FORM = "SET_SUMMITTING_USER_FORM",
}

export default ActionTypes;
